alter table actor_role drop foreign key if exists FK2x71qf5w1n93pki686nbhsxqm;
alter table actor_role drop foreign key if exists FK7nixnkawckbp6e6d7x0f5pby6;
alter table company_movies drop foreign key if exists FKmmc8rt6ss635b1nrybown4va2;
alter table company_movies drop foreign key if exists FKknnnj0j6wcph9jgfn2bcd4ky6;
alter table country_movies drop foreign key if exists FKpygrtf1pvsg7g61jprlk308m8;
alter table country_movies drop foreign key if exists FKpxkrflndnuuvgs4n7pj2sqlpx;
alter table genre_movies drop foreign key if exists FKtgatsvi7lb98phh9ft1gogkep;
alter table genre_movies drop foreign key if exists FKe8j9am8l355522fj88clwhbt8;
alter table language_movies drop foreign key if exists FK78fnn8j50f8md8o3ajkdp346l;
alter table language_movies drop foreign key if exists FKv00xsh77h5m3pcr1b1n29j5a;
drop table if exists actor;
drop table if exists actor_role;
drop table if exists company;
drop table if exists company_movies;
drop table if exists country;
drop table if exists country_movies;
drop table if exists genre;
drop table if exists genre_movies;
drop table if exists language;
drop table if exists language_movies;
drop table if exists movie;
alter table actor_role drop foreign key if exists FK2x71qf5w1n93pki686nbhsxqm;
alter table actor_role drop foreign key if exists FK7nixnkawckbp6e6d7x0f5pby6;
alter table company_movies drop foreign key if exists FKmmc8rt6ss635b1nrybown4va2;
alter table company_movies drop foreign key if exists FKknnnj0j6wcph9jgfn2bcd4ky6;
alter table country_movies drop foreign key if exists FKpygrtf1pvsg7g61jprlk308m8;
alter table country_movies drop foreign key if exists FKpxkrflndnuuvgs4n7pj2sqlpx;
alter table genre_movies drop foreign key if exists FKtgatsvi7lb98phh9ft1gogkep;
alter table genre_movies drop foreign key if exists FKe8j9am8l355522fj88clwhbt8;
alter table language_movies drop foreign key if exists FK78fnn8j50f8md8o3ajkdp346l;
alter table language_movies drop foreign key if exists FKv00xsh77h5m3pcr1b1n29j5a;
drop table if exists actor;
drop table if exists actor_role;
drop table if exists company;
drop table if exists company_movies;
drop table if exists country;
drop table if exists country_movies;
drop table if exists genre;
drop table if exists genre_movies;
drop table if exists language;
drop table if exists language_movies;
drop table if exists movie;
